name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Checking your code format
        run: sbt scalafmtCheck
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Set up jekyll
        if: env.REQUIRES_JEKYLL_CI != null
        run: |
          gem install jekyll -v 4
      - name: Run tests and documentation
        run: |
          csbt +test packageSrc docs/mdoc
