name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checking code formatting
        uses: openlawteam/scalafmt-ci@v2
        with:
          args: "core dotSyntax macro --exclude=third_party --list"
      - name: Run tests
        run: |
          sbt +monocleJVM/test +monocleJS/test packageSrc
          SCALAJS_VERSION=1.0.0-rc1 sbt +monocleJS/test
